name: release

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'lib/**/version.rb'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Release
      run: bundle exec rake release
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
